# Generated by Django 3.0 on 2019-12-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0004_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
