# Generated by Django 3.0 on 2019-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0005_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Mobile_No',
            field=models.BigIntegerField(),
        ),
    ]
