# Generated by Django 3.0 on 2020-01-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0008_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='courseID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
