# Generated by Django 3.0 on 2020-01-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0009_enrollment_courseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='courseID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
