# Generated by Django 3.0 on 2020-01-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0010_auto_20200114_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('CourseID', models.CharField(choices=[('CVE1', 'CVE1'), ('CVM2', 'CVM2'), ('CVS3', 'CVS3'), ('CVP4', 'CVP4'), ('CVB5', 'CVB5'), ('CVC6', 'CVC6'), ('CVCS7', 'CVCS7'), ('CRE1', 'CRE1'), ('CRM2', 'CRM2'), ('CRS3', 'CRS3'), ('CRP4', 'CRP4'), ('CRB5', 'CRB5'), ('CRSC6', 'CRSC6'), ('CBC1', 'CBC1'), ('CBE2', 'CBE2'), ('CBC3', 'CBC3'), ('CBM4', 'CBM4'), ('CBSC5', 'CBSC5'), ('CME1', 'CME1'), ('CMM2', 'CMM2'), ('CMS3', 'CMS3'), ('CMB4', 'CMB4'), ('CMC5', 'CMC5'), ('CME6', 'CME6'), ('CMCS7', 'CMCS7'), ('CPE1', 'CPE1'), ('CPC2', 'CPC2'), ('CPE3', 'CPE3'), ('CPCS4', 'CPCS4'), ('CPM5', 'CPM5'), ('CTE1', 'CTE'), ('CTM2', 'CTM2'), ('CTS3', 'CTS3'), ('CTP4', 'CTP4'), ('CTB5', 'CTB5'), ('CSE1', 'CSE1'), ('CSM2', 'CSM2'), ('CSS3', 'CSS3'), ('CSP4', 'CSP4'), ('CSB5', 'CSB5'), ('CSC6', 'CSC6'), ('CSE7', 'CSE7'), ('CSC8', 'CSC8'), ('CHE1', 'CHE1'), ('CHM2', 'CHM2'), ('CHS3', 'CHS3'), ('CHP4', 'CHP4'), ('CHB5', 'CHB5'), ('CHCS6', 'CHCS6'), ('CPRE1', 'CPRE1'), ('CPRM2', 'CPRM2'), ('CPRP3', 'CPRP3'), ('CPRB4', 'CPRB4'), ('CPRCS5', 'CPRCS5'), ('CHME1', 'CHME1'), ('CHMM2', 'CHMM2'), ('CHMP3', 'CHMP3'), ('CHMB4', 'CHMB4'), ('CHME5', 'CHME5'), ('CRE1', 'CRE1')], max_length=200, null=True)),
                ('Mobile_No', models.IntegerField()),
            ],
        ),
    ]
