# Generated by Django 3.0 on 2020-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0011_enrollmentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='Mobile_No',
            field=models.BigIntegerField(),
        ),
    ]
