# Generated by Django 3.0 on 2020-01-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0012_auto_20200115_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='institute_names',
            field=models.CharField(choices=[('Vivekananda foundation', 'Vivekananda foundation'), ('Ragatuition', 'Ragatuition'), ('BRILLIANT ACADEMY', 'BRILLIANT ACADEMY'), ('MelhorInstitute', 'MelhorInstitute'), ('Prasads-Educational-Institutions', 'Prasads-Educational-Institutions'), ('TeachingFish', 'TeachingFish'), ('Srinivasa Coaching Center', 'Srinivasa Coaching Center'), ('Home Tuitions', 'Home Tuitions'), ('Prism Coaching Center', 'Prism Coaching Center'), ('Hemtor Tuitions', 'Hemtor Tuitions')], max_length=200, null=True),
        ),
    ]
