# Generated by Django 3.0 on 2020-01-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0014_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TuitionWala.EnrollmentForm')),
                ('institute_names', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TuitionWala.Enrollment')),
            ],
        ),
    ]
