# Generated by Django 3.0 on 2020-01-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0015_test_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_example',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='test_example',
            name='institute_names',
        ),
        migrations.RenameField(
            model_name='enrollmentform',
            old_name='institute_names',
            new_name='Institute_Name',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Test_example',
        ),
    ]
