# Generated by Django 3.0 on 2020-01-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0016_auto_20200117_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollmentForm',
            new_name='EnrollmentForm_Table',
        ),
    ]
