# Generated by Django 3.0 on 2020-01-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0018_auto_20200118_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentform_table',
            old_name='Name',
            new_name='Student_Name',
        ),
    ]
