# Generated by Django 3.0 on 2020-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0019_auto_20200118_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entity_Name', models.CharField(max_length=200)),
                ('Entity_Type', models.CharField(choices=[('FACULTY/TUTOR', 'FACULTY/TUTOR'), ('INSTITUTION', 'INSTITUTION')], max_length=200)),
                ('Academic_Qualification_IF_Tutor', models.CharField(max_length=300)),
                ('Years_Of_Establishment_IF_Institution', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Subject_1', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200)),
                ('Subject_2', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200)),
                ('Subject_3', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200)),
                ('Subject_4', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200)),
                ('Subject_5', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200)),
                ('Subject_6', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200)),
            ],
        ),
    ]
