# Generated by Django 3.0 on 2020-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0020_teaching_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_1_Fee',
            field=models.CharField(choices=[('500-1000 Per Month', '500-1000 Per Month'), ('1000-1500 Per Month', '1000-1500 Per Month'), ('1500-2000 Per Month', '1500-2000 Per Month'), ('Above 2000 Per Month', 'Above 2000 Per Month')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_2_Fee',
            field=models.CharField(choices=[('500-1000 Per Month', '500-1000 Per Month'), ('1000-1500 Per Month', '1000-1500 Per Month'), ('1500-2000 Per Month', '1500-2000 Per Month'), ('Above 2000 Per Month', 'Above 2000 Per Month')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_3_Fee',
            field=models.CharField(choices=[('500-1000 Per Month', '500-1000 Per Month'), ('1000-1500 Per Month', '1000-1500 Per Month'), ('1500-2000 Per Month', '1500-2000 Per Month'), ('Above 2000 Per Month', 'Above 2000 Per Month')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_4_Fee',
            field=models.CharField(choices=[('500-1000 Per Month', '500-1000 Per Month'), ('1000-1500 Per Month', '1000-1500 Per Month'), ('1500-2000 Per Month', '1500-2000 Per Month'), ('Above 2000 Per Month', 'Above 2000 Per Month')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_5_Fee',
            field=models.CharField(choices=[('500-1000 Per Month', '500-1000 Per Month'), ('1000-1500 Per Month', '1000-1500 Per Month'), ('1500-2000 Per Month', '1500-2000 Per Month'), ('Above 2000 Per Month', 'Above 2000 Per Month')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_6_Fee',
            field=models.CharField(choices=[('500-1000 Per Month', '500-1000 Per Month'), ('1000-1500 Per Month', '1000-1500 Per Month'), ('1500-2000 Per Month', '1500-2000 Per Month'), ('Above 2000 Per Month', 'Above 2000 Per Month')], max_length=200, null=True),
        ),
    ]
