# Generated by Django 3.0 on 2020-01-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0022_auto_20200121_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching_form',
            name='Academic_Qualification_IF_Tutor',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teaching_form',
            name='Years_Of_Establishment_IF_Institution',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
