# Generated by Django 3.0 on 2020-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuitionWala', '0023_auto_20200121_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching_form',
            name='Subjects',
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_1',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_2',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_3',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_4',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_5',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teaching_form',
            name='Subject_6',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('SOCIAL', 'SOCIAL'), ('PHYSICS', 'PHYSICS'), ('BIOLOGY', 'BIOLOGY'), ('COMMERCE', 'COMMERCE'), ('ECONOMICS', 'ECONOMICS'), ('CIVICS', 'CIVICS'), ('COMPUTER SCIENCES', 'COMPUTER SCIENCES')], max_length=200, null=True),
        ),
    ]
